#!/bin/sh -ex

nodes=$1
cmd=$2
algorithm=$3
matrix=$4
n_runs=$5
n_warmup=$6

id=$(date +"%Y-%m-%d-%T")
run_path="runs/$id-$nodes"
mkdir -p "$run_path" 

# If we use this script, we always want to persist results!
# -> Last arg = true
mpirun -n "$nodes" "$cmd" "$algorithm" "$matrix" "$run_path" "$n_runs" "$n_warmup" "true" | sort -s -t '[' -k2,2n
